replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths: 
        - path: /dev
          pathType: Prefix
          serviceName: "helm-dev-app-simple-chart"
        - path: /prod
          pathType: Prefix
          serviceName: "helm-prod-app-simple-chart"
        - path: /staging
          pathType: Prefix
          serviceName: "helm-staging-app-simple-chart"

resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

healthCheck:
  livenessPath: /
  readinessPath: /

secrets:
  OPENROUTER_API_KEY:
    secretName: app-secrets
    secretKey: OPENROUTER_API_KEY
