replicaCount: 2

image:
  repository: nginx
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths: 
        - path: /dev
          pathType: Prefix
          serviceName: "dev-app"
        - path: /prod
          pathType: Prefix
          serviceName: "prod-app"
        - path: /staging
          pathType: Prefix
          serviceName: "staging-app"

resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

healthCheck:
  livenessPath: /
  readinessPath: /
