apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-chart.fullname" . }}
  labels:
    {{- include "simple-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-chart.labels" . | nindent 8 }}
    template:
     metadata:
      labels:
        {{- include "simple-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENROUTER_API_KEY
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessPath }}
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessPath }}
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}