{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-chart.fullname" . }}
  labels:
    {{- include "simple-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.hosts }}
  rules:
  {{- range .Values.ingress.hosts }}
    - {{- if .host }}host: {{ .host | quote }}{{- end }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ .serviceName | default (include "simple-chart.fullname" $) }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
