{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-chart.fullname" . }}
  labels:
    {{- include "simple-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ default "" (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          {{- range (index .Values.ingress.hosts 0).paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ .serviceName | default (include "simple-chart.fullname" $) }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}