image:
  repository: omerteomim/dev-app
  tag: "20250818175236"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /dev
          pathType: Prefix
          serviceName: "helm-dev-app-simple-chart"